### PR TITLE
Update

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Hi.

This PR updates the source to be more idomatic as well as to compile with a current nightly.
I also cleans up the codebase and adds some features even.

If you want me to break this up into smaller PRs, feel free to request that.
I did **NOT YET** test-run this version.
If you want to wait until I did, that's fine.

---

Each patch should be reviewed individually!

### CODE REVIEW

**Comment by mario-kr** [comment]
Yes, please do a test-run

**Comment by mario-kr** [comment]
Project might need to be renamed... I used "aklog" as a short version of antikoerper-log

**Comment by mario-kr** [comment]
Though I don't encourage using this little program either way. Timeseries-DBs like influxdb are better suited and queries on them are faster, especially with more data

**Comment by matthiasbeyer** [comment]
Names are just names. I wouldn't rename it. Doesn't matter, does it?

**Pull request merged**
